name: Test Docker Build

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: audio2tonie:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test container functionality
        run: |
          docker build -t audio2tonie:test .
          # Test that the container runs without errors
          docker run --rm audio2tonie:test opus2tonie --help
          docker run --rm audio2tonie:test transcode --help || true
          echo "✅ Container build and basic functionality test passed"
